print("Hello World")
print("Samarth Bhosdika")
print("Roshan Badhva")
print("Ayush ch0odh dete hai")
print("Sanvi chomu")
print("Achal Rndwa")
print("Raghav chinnar")
print("Madhav gelchodha")
print("Chinmay chutmari ka")