import os
from dotenv import load_dotenv

# Load environment variables from .env
load_dotenv()

AIVEN_PASSWORD = os.getenv("AIVEN_PASSWORD")

# EMAIL BACKEND
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('myemail')  # your gmail
EMAIL_HOST_PASSWORD = os.getenv('mypass')  # your app password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

"""
Django settings for first project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.urls import reverse_lazy
import cloudinary
import cloudinary.uploader
import cloudinary.api


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xsb1!c&3(6@om=94)nx&xv(!s(w$-r+2$w7s_o!=0l@%djrpe2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home.apps.HomeConfig',
    'cloudinary',
    'cloudinary_storage',
]

cloudinary.config(
    cloud_name='doqajnknv',
    api_key='628619454961221',
    api_secret='fQxxb_Bj31dHJGBBo848uyfY4Jw',
)

CLOUDINARY_STORAGE={

    'CLOUD_NAME':'doqajnknv',
    'API_KEY':'628619454961221',
    'API_SECRET':'fQxxb_Bj31dHJGBBo848uyfY4Jw',
}

DEFAULT_FILE_STORAGE='cloudinary_storage.storage.MediaCloudinaryStorage'


SITE_ID=2


SOCIALACCOUNT_LOGIN_ON_GET = True

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = 'profilepage'   # where to go after login
LOGOUT_REDIRECT_URL = '/'  # where to go after logout
ACCOUNT_LOGOUT_ON_GET = True

ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'email'}

ACCOUNT_SIGNUP_REDIRECT_URL = '/account/email-verification-sent/'
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = 'profilepage'
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = '/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'doubtoclock@gmail.com'
EMAIL_HOST_PASSWORD = 'jvijckaqhautxkhx'  # <-- paste your App Password here



SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': "333696078031-s1mel092n3orcigegbepsnvf5qe3n51o.apps.googleusercontent.com",
            'secret': "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",
            'key': ""
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    }
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'first.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'first.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'defaultdb',      # database name
        'USER': 'avnadmin',      # MySQL username
        'PASSWORD': AIVEN_PASSWORD,  # MySQL password
        'HOST': 'mysql-36f7ea44-chinmaysabharwal123-4568.l.aivencloud.com',         # or your MySQL server IP
        'PORT': '26742',              # default MySQL port
        "OPTIONS": {
            "ssl": {"ca": str(BASE_DIR / "certs/ca.pem")}
        }
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# Added Manually 
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


