# Generated by Django 5.2.5 on 2025-10-05 06:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Doubt",
            new_name="Doubt_jn",
        ),
    ]
